version: "3.8"

services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: your_database
      PORT: 3006
    depends_on:
      - mysql
    ports:
      - "3006:3006"

  mysql:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
